name: smart_farm
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  dio: ^5.7.0
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  go_router: ^14.6.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  http_parser: ^4.0.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  lottie: ^3.1.3
  shared_preferences: ^2.3.3
  data_layer:
    path: ../data_layer
  carousel_slider: ^5.0.0
  signalr_core: ^1.1.2
  web_socket_channel: ^2.4.3
  web: ^0.5.0
  freezed_annotation: ^2.4.4
  flutter_native_splash: ^2.4.3
  flutter_background_service: ^5.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: true
  image_path: "assets/images/LOGOOFFICIAL.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/LOGOOFFICIAL.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/animations/
    - .env

flutter_native_splash:
  android: true
  ios: false
  web: false

  color: "#379C3B" # Green color
  image: "assets/images/LOGOOFFICIAL.png"

  android_12:
    color: "#379C3B" # Green color
    image: "assets/images/LOGOOFFICIAL.png"
